[tools]
java = "17"

"pre-commit" = "latest"


[tasks.dev]
run = "./gradlew run"

[tasks.test]
run = "./gradlew test"

[tasks.build]
run = "./gradlew build"

[tasks.clean]
run = "./gradlew clean"

[tasks.format]
run = "./gradlew spotlessApply"

[tasks.lint]
run = "./gradlew spotlessCheck"
